### ISSUE TITLE
error when i transfer ownership to someone

### ISSUE THREAD

**Issue by dante201** [DeadBread76/Discord-Ownership-transfer#1]
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\aCer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\aCer\Desktop\main.py", line 15, in on_ready
    server = client.get_server(SERVER)
AttributeError: 'Client' object has no attribute 'get_server'
![Screenshot (16)](https://user-images.githubusercontent.com/78878885/107567866-4f82d300-6bf7-11eb-8b71-deca26893888.png)

**Comment by pIague** [comment]
> Ignoring exception in on_ready
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\aCer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 343, in _run_event
> 
>     await coro(*args, **kwargs)
> 
>   File "C:\Users\aCer\Desktop\main.py", line 15, in on_ready
> 
>     server = client.get_server(SERVER)
> 
> AttributeError: 'Client' object has no attribute 'get_server'
> 
> ![Screenshot (16)](https://user-images.githubusercontent.com/78878885/107567866-4f82d300-6bf7-11eb-8b71-deca26893888.png)
> 
> 

did you find a fix?

**Comment by HaydernOrigin** [comment]
i need  some hel pwith this
